#!/bin/bash

# SHOPIX MongoDB to MySQL Conversion - Batch Script
# This script provides templates for converting remaining API routes

echo "=== SHOPIX MongoDB to MySQL Batch Converter ==="
echo ""
echo "✅ Already Converted (11 files):"
echo "  - Auth: login, signup"
echo "  - Products: GET/POST, PUT/DELETE, marketplace"
echo "  - Cart: POST/GET/DELETE"
echo "  - Orders: POST/GET/PATCH, user orders"
echo "  - Wishlist: POST/GET/DELETE, move-to-cart"
echo "  - Reviews: POST"
echo "  - Notifications: GET, PATCH, mark-all-read"
echo "  - Chat: conversations"
echo ""
echo "⏳ Still Need Conversion (18 files):"
echo ""
echo "PRIORITY 1 - Core Auth & User:"
echo "  1. src/app/api/auth/verifyemail/route.ts"
echo "  2. src/app/api/auth/forgetpassword/route.ts"
echo "  3. src/app/api/auth/user/route.ts"
echo "  4. src/app/api/auth/deleteaccount/route.ts"
echo ""
echo "PRIORITY 2 - Chat & Messaging:"
echo "  5. src/app/api/chat/conversation/route.ts"
echo "  6. src/app/api/chat/[conversationId]/route.ts"
echo ""
echo "PRIORITY 3 - Store Management:"
echo "  7. src/app/api/store/route.ts"
echo "  8. src/app/api/store/manage/route.ts"
echo "  9. src/app/api/admin/stores/[id]/route.ts"
echo ""
echo "PRIORITY 4 - Admin & Analytics:"
echo "  10. src/app/api/admin/dashboard/route.ts"
echo "  11. src/app/api/admin/users/route.ts"
echo "  12. src/app/api/store/sales-analytics/route.ts"
echo ""
echo "PRIORITY 5 - Additional Features:"
echo "  13. src/app/api/orders/return/route.ts"
echo "  14. src/app/api/notifications/[id]/route.ts (Already done)"
echo "  15. src/app/api/marketplace/products/[id]/route.ts"
echo "  16. src/app/api/store/admin/review/route.ts"
echo "  17. src/app/api/create-payment-intent/route.ts"
echo "  18. src/app/api/chatbot/route.ts"
echo ""
echo "=== NEXT STEPS ==="
echo ""
echo "1. For each remaining file, follow this pattern:"
echo ""
echo "   OLD: import connectDB, Model from mongoose"
echo "   NEW: import pool from @/src/lib/db"
echo ""
echo "   OLD: await connectDB()"
echo "   NEW: (remove - pool handles connection)"
echo ""
echo "   OLD: await Model.find(query)"
echo "   NEW: const [rows] = await pool.execute('SELECT...', [values])"
echo ""
echo "2. Replace Mongoose operations:"
echo "   - find() → SELECT"
echo "   - findById() → SELECT WHERE id ="
echo "   - findOne() → SELECT LIMIT 1"
echo "   - create() → INSERT"
echo "   - updateOne() → UPDATE"
echo "   - deleteOne() → DELETE"
echo "   - populate() → JOIN"
echo "   - sort() → ORDER BY"
echo "   - limit() → LIMIT"
echo ""
echo "3. Handle MySQL result format:"
echo "   - const [rows] = await pool.execute('...')"
echo "   - rows is array of results"
echo "   - Use rows[0] for single result"
echo ""
echo "4. Always use parameterized queries:"
echo "   - GOOD: pool.execute('WHERE id = ?', [userId])"
echo "   - BAD: pool.execute('WHERE id = ' + userId)"
echo ""
echo "5. Build complex queries with JOINs:"
echo ""
echo "   SELECT u.*, p.name FROM users u"
echo "   JOIN products p ON u.id = p.seller_id"
echo "   WHERE u.role = ?"
echo ""
echo "=== IMPLEMENTATION CHECKLIST ====="
echo ""
echo "For each file conversion:"
echo "  □ Remove all Mongoose imports"
echo "  □ Import pool from @/src/lib/db"
echo "  □ Remove connectDB() calls"
echo "  □ Convert all queries to SQL"
echo "  □ Use parameterized queries"
echo "  □ Handle result format properly"
echo "  □ Update error messages"
echo "  □ Test the endpoint"
echo ""
echo "=== COMMON PATTERNS ====="
echo ""
echo "1. GET user's items:"
echo "   const [items] = await pool.execute("
echo "     'SELECT * FROM table WHERE user_id = ? ORDER BY created_at DESC',"
echo "     [userId]"
echo "   );"
echo ""
echo "2. INSERT with return ID:"
echo "   const [result] = await pool.execute("
echo "     'INSERT INTO table (col1, col2) VALUES (?, ?)',"
echo "     [value1, value2]"
echo "   );"
echo "   const newId = result.insertId;"
echo ""
echo "3. UPDATE specific record:"
echo "   await pool.execute("
echo "     'UPDATE table SET col = ? WHERE id = ? AND user_id = ?',"
echo "     [newValue, id, userId]"
echo "   );"
echo ""
echo "4. COUNT:"
echo "   const [countResult] = await pool.execute("
echo "     'SELECT COUNT(*) as count FROM table WHERE ...'"
echo "   );"
echo "   const count = countResult[0].count;"
echo ""
echo "5. JOIN for related data:"
echo "   const [rows] = await pool.execute("
echo "     'SELECT u.*, p.name FROM users u"
echo "      JOIN products p ON u.id = p.seller_id"
echo "      WHERE u.id = ?',"
echo "     [userId]"
echo "   );"
echo ""
echo "=== TESTING ====="
echo ""
echo "After each conversion, test:"
echo "  npm run build  # Check for TypeScript errors"
echo "  curl http://localhost:3000/api/endpoint  # Test the endpoint"
echo ""
echo "All conversions use same pool connection - just different SQL!"
echo "Remember: pool.execute() returns [rows, fields]"
echo ""
